GAME_WIDTH = 960
GAME_HEIGHT = 540
GRID_SIZE_W = 25
GRID_SIZE_H = 12
NUMBER_OF_CELLS = GRID_SIZE_W * GRID_SIZE_H
NUMBER_OF_MINES = NUMBER_OF_CELLS // 6
BUTTON_SIDE = 30
CELLS_POS = 30

seconds = 0
